'use strict';

// Question bank for /trivia. Trading questions are deliberately factual/
// definitional (what a term means) rather than strategy ("when should you
// buy") — the bot isn't in the business of giving trading advice. Politics
// questions are the same idea: historical/civics facts (who, how many, how
// long), never current-events opinion or policy takes.
//
// Each entry: { q, choices: [4], correct: index of the right choice }.

const QUESTIONS = {
  trading: [
    { q: "What does 'IPO' stand for?", choices: ['Initial Public Offering', 'Internal Profit Order', 'Investment Portfolio Option', 'Interbank Payment Order'], correct: 0 },
    { q: "What is a 'bull market'?", choices: ['A market with high volatility', 'A market where prices are generally rising', 'A market only for commodities', 'A market closed for trading'], correct: 1 },
    { q: "What is a 'bear market'?", choices: ['A market where prices are generally falling', 'A market with no volume', 'A market for bonds only', 'A market open 24/7'], correct: 0 },
    { q: "What does 'liquidity' refer to in trading?", choices: ['How profitable an asset is', 'How easily an asset can be bought or sold without affecting its price', 'The tax rate on an asset', "An asset's dividend yield"], correct: 1 },
    { q: 'What is a dividend?', choices: ['A fee charged by brokers', 'A portion of a company\'s profit paid to shareholders', 'A type of stock exchange', 'A government bond'], correct: 1 },
    { q: "What does 'ETF' stand for?", choices: ['Exchange Traded Fund', 'Equity Transfer Form', 'Electronic Trading Facility', 'External Trade Function'], correct: 0 },
    { q: 'What is short selling?', choices: ['Buying a stock for a short time only', 'Selling a borrowed asset hoping to buy it back cheaper later', 'Selling a stock below its opening price', 'A same-day-only trade'], correct: 1 },
    { q: "What does 'P/E ratio' stand for?", choices: ['Profit/Earnings ratio', 'Price/Earnings ratio', 'Position/Equity ratio', 'Payout/Expense ratio'], correct: 1 },
    { q: "What is a 'blue chip' stock?", choices: ['A newly listed penny stock', 'A stock of a large, financially stable, well-established company', 'A stock that only trades on weekends', 'A stock with no dividend history'], correct: 1 },
    { q: "What does 'NYSE' stand for?", choices: ['New York Stock Exchange', 'National Yield Securities Exchange', 'New York Securities Entity', 'North Yield Stock Exchange'], correct: 0 },
    { q: "What is a 'stop-loss' order?", choices: ['An order that cancels all your other orders', 'An order that automatically sells a position once it hits a set price', 'An order only usable once per day', 'A type of dividend reinvestment'], correct: 1 },
    { q: 'What does market capitalization measure?', choices: ["A company's total debt", "A company's total revenue", "The total market value of a company's outstanding shares", "A company's annual profit"], correct: 2 },
    { q: 'What is a stock split?', choices: ["A company dividing its shares into multiple shares to lower the price per share", 'When a company goes bankrupt', 'A merger between two companies', "A type of dividend paid in cash"], correct: 0 },
    { q: "What does 'volatility' measure in markets?", choices: ["A company's headcount", "How much and how quickly a price moves", "The number of shares outstanding", "The interest rate on a bond"], correct: 1 },
    { q: 'What is a limit order?', choices: ['An order executed immediately at any price', 'An order that can only be placed once per day', 'An order to buy or sell at a specific price or better', 'An order that expires after one minute'], correct: 2 },
    { q: "What does 'NASDAQ' primarily list?", choices: ['Only government bonds', 'Mostly technology and growth companies', 'Only commodities', 'Only foreign currencies'], correct: 1 },
    { q: 'What is a mutual fund?', choices: ['A loan between two companies', 'A pooled investment managed by a professional fund manager', 'A type of savings account', 'A government-issued bond'], correct: 1 },
    { q: "What does 'bid-ask spread' refer to?", choices: ["A company's profit margin", 'The difference between the highest buy offer and lowest sell offer', "A stock's dividend history", "A trader's win rate"], correct: 1 },
    { q: 'What is a futures contract?', choices: ['A stock that pays no dividend', 'An agreement to buy or sell an asset at a set price on a future date', 'A type of savings bond', 'A loan with no interest'], correct: 1 },
    { q: "What does 'ticker symbol' mean?", choices: ["A company's tax ID", 'The abbreviation used to identify a publicly traded stock', "A stock's exchange rate", "A broker's license number"], correct: 1 },
    { q: 'What is an index fund?', choices: ['A fund that tracks a market index like the S&P 500', 'A fund that only holds one stock', 'A fund exclusive to banks', 'A type of insurance product'], correct: 0 },
    { q: "What does 'going long' on a stock mean?", choices: ['Buying it expecting the price to rise', 'Selling it expecting the price to fall', 'Holding it for exactly one year', 'Buying it with borrowed money only'], correct: 0 },
    { q: "What does 'AUM' stand for in fund management?", choices: ['Assets Under Management', 'Annual Underwriting Margin', 'Average Unit Multiplier', 'Adjusted Uniform Metric'], correct: 0 },
    { q: "What is a 'pip' in forex trading?", choices: ['A type of broker fee', 'The smallest standard price movement in a currency pair', 'A currency reserve requirement', 'A type of futures contract'], correct: 1 },
    { q: "What does 'leverage' mean in trading?", choices: ['Trading only with cash on hand', 'Using borrowed capital to increase potential returns', 'A guaranteed minimum return', 'A type of dividend'], correct: 1 },
    { q: "What is a 'margin call'?", choices: ["A broker's demand for more funds when an account falls below the required margin", 'A call option that expired', 'A daily account statement', "A stock's opening price announcement"], correct: 0 },
    { q: "What does 'OTC' stand for in trading?", choices: ['On-The-Clock', 'Over-The-Counter', 'Open Trade Contract', 'Official Trading Certificate'], correct: 1 },
    { q: "What is a 'penny stock'?", choices: ['A stock that pays dividends in cash only', 'A stock that typically trades at a very low share price', 'A stock traded only once a year', 'A stock exclusive to pension funds'], correct: 1 },
    { q: 'What is day trading?', choices: ['Holding a position for at least a year', 'Buying and selling securities within the same trading day', 'Trading only government bonds', 'A trade that settles over a weekend'], correct: 1 },
    { q: "What does 'DCA' stand for as an investing strategy?", choices: ['Direct Capital Allocation', 'Dollar-Cost Averaging', 'Deferred Credit Agreement', 'Daily Cash Adjustment'], correct: 1 },
    { q: 'What is a call option?', choices: ['A contract giving the right to sell an asset at a set price', 'A contract giving the right to buy an asset at a set price', 'A guaranteed dividend payment', 'A type of margin loan'], correct: 1 },
    { q: 'What is a put option?', choices: ['A contract giving the right to sell an asset at a set price', 'A contract giving the right to buy an asset at a set price', 'A type of stock split', 'A fixed-income bond'], correct: 0 },
    { q: 'What is a hedge in trading?', choices: ['A trade made purely for speculation', 'An investment made to reduce the risk of adverse price movements', 'A type of broker commission', 'A guaranteed-profit trade'], correct: 1 },
    { q: "What does 'NAV' stand for in fund investing?", choices: ['Net Asset Value', 'National Average Valuation', 'New Account Verification', 'Net Annual Volume'], correct: 0 },
    { q: 'What is a circuit breaker in stock markets?', choices: ['A tool that speeds up trade execution', 'A mechanism that temporarily halts trading after a steep decline', "A broker's backup power system", 'A type of margin account'], correct: 1 },
    { q: "What does 'YTD' mean in a performance report?", choices: ['Yield To Date', 'Year-To-Date', 'Yearly Trade Deduction', 'Yield Total Distribution'], correct: 1 },
    { q: "What is 'slippage' in trading?", choices: ["A broker's error rate", 'The difference between the expected price of a trade and the actual executed price', 'A tax on short-term gains', 'A delay in dividend payments'], correct: 1 },
    { q: 'What is a candlestick chart primarily used for?', choices: ['Tracking dividend payment dates', 'Visualizing price movement over time', 'Listing company executives', 'Calculating tax liability'], correct: 1 },
    { q: 'What does it mean to "diversify" a portfolio?', choices: ['Investing everything in one asset', 'Spreading investments across different assets to reduce risk', 'Selling all holdings at once', 'Only holding cash'], correct: 1 },
    { q: 'What is a "bear trap" in trading slang?', choices: ['A guaranteed losing trade', 'A false signal suggesting a price decline that reverses upward', 'A type of stop-loss order', 'A broker fee structure'], correct: 1 },
    { q: 'What does "buy the dip" mean?', choices: ['Selling after a price increase', 'Buying an asset after its price has fallen, expecting a rebound', 'Buying only at market open', 'Avoiding a stock entirely'], correct: 1 },
  ],

  economics: [
    { q: "What does 'GDP' stand for?", choices: ['Gross Domestic Product', 'General Debt Payment', 'Government Development Plan', 'Global Direct Pricing'], correct: 0 },
    { q: 'What does inflation mean?', choices: ['A general decrease in prices over time', 'A general increase in prices over time', 'A fixed exchange rate', "A country's total exports"], correct: 1 },
    { q: 'What is the primary role of a central bank?', choices: ['Running the stock exchange', "Managing a country's monetary policy and currency", 'Collecting income taxes', 'Regulating food safety'], correct: 1 },
    { q: 'What is typically used to define a recession?', choices: ['One quarter of rising unemployment', 'Two consecutive quarters of negative GDP growth', 'A single day of stock market decline', 'Any year with inflation above 5%'], correct: 1 },
    { q: "What does 'supply and demand' describe?", choices: ['A type of tax policy', 'The relationship between availability of a product and desire for it, which affects price', "A country's export/import ratio", 'A banking regulation'], correct: 1 },
    { q: 'What is fiscal policy?', choices: ["A central bank's interest rate decisions", "Government use of spending and taxation to influence the economy", 'A company\'s annual budget', 'An exchange rate agreement between countries'], correct: 1 },
    { q: 'What is monetary policy?', choices: ["A government's spending plan", "A central bank's actions to manage money supply and interest rates", 'A company\'s pricing strategy', 'An international trade agreement'], correct: 1 },
    { q: 'What does the unemployment rate measure?', choices: ['Total population of a country', 'The percentage of the labor force that is jobless and looking for work', "A country's GDP growth", 'The average wage in a country'], correct: 1 },
    { q: "What does 'CPI' stand for?", choices: ['Consumer Price Index', 'Corporate Profit Indicator', 'Central Payment Instrument', 'Currency Parity Index'], correct: 0 },
    { q: 'Which US institution sets the federal funds rate?', choices: ['The US Treasury', 'The Federal Reserve', 'The New York Stock Exchange', 'Congress'], correct: 1 },
    { q: 'What is a trade deficit?', choices: ['When a country exports more than it imports', 'When a country imports more than it exports', "A company's annual loss", 'A tax on foreign goods'], correct: 1 },
    { q: 'What does GDP per capita measure?', choices: ['Total government debt', 'Average economic output per person in a country', "A country's total population", 'The exchange rate of a currency'], correct: 1 },
    { q: 'What is deflation?', choices: ['A general increase in prices over time', 'A general decrease in prices over time', 'A fixed currency exchange rate', 'A rise in interest rates only'], correct: 1 },
    { q: "What does 'stagflation' describe?", choices: ['High growth with low inflation', 'Stagnant growth combined with high inflation', 'Zero unemployment', 'A currency pegged to gold'], correct: 1 },
    { q: 'What is a tariff?', choices: ['A tax imposed on imported goods', 'A subsidy for domestic farmers', 'A type of interest rate', "A country's credit rating"], correct: 0 },
    { q: "What does 'per capita income' mean?", choices: ['Total national income', 'Average income per person in a population', "A company's total revenue", 'The minimum wage in a country'], correct: 1 },
    { q: 'What is a subsidy?', choices: ['A tax on exports', 'Financial support given by a government to a business or sector', 'A type of loan between banks', 'A fine for pollution'], correct: 1 },
    { q: "What does the term 'labor force' refer to?", choices: ['Only unemployed people', 'People who are employed or actively seeking work', 'Only government employees', 'People under 18'], correct: 1 },
    { q: 'What is currency devaluation?', choices: ["A deliberate downward adjustment of a country's currency value relative to others", 'An increase in a currency\'s value', 'A ban on foreign currency trading', "A country's total debt level"], correct: 0 },
    { q: 'What is a budget deficit?', choices: ['When government spending exceeds its revenue', 'When government revenue exceeds its spending', "A company's annual loss", 'A trade imbalance between countries'], correct: 0 },
    { q: "What does 'PPP' stand for in economics?", choices: ['Purchasing Power Parity', 'Public Price Policy', 'Private Production Plan', 'Periodic Payment Plan'], correct: 0 },
    { q: "What is 'opportunity cost'?", choices: ['The tax paid on an investment', 'The value of the next best alternative given up when making a choice', "A company's total operating cost", 'The interest rate on a loan'], correct: 1 },
    { q: 'What does quantitative easing involve?', choices: ['A central bank raising interest rates sharply', 'A central bank buying assets to inject money into the economy', 'A government cutting all public spending', 'A country banning foreign investment'], correct: 1 },
    { q: 'What is a command economy?', choices: ['An economy where prices are set purely by supply and demand', 'An economy where the government controls production and pricing decisions', 'An economy with no currency', 'An economy run entirely by corporations'], correct: 1 },
    { q: 'What is a free market economy?', choices: ['An economy where prices are determined by supply and demand with minimal government intervention', 'An economy where the government sets all prices', 'An economy with no private property', 'An economy based only on barter'], correct: 0 },
    { q: "What does the 'Gini coefficient' measure?", choices: ["A country's GDP growth rate", 'Income inequality within a population', 'A currency\'s exchange rate', 'A company\'s market share'], correct: 1 },
    { q: 'What is hyperinflation?', choices: ['A slow, steady rise in prices', 'Extremely rapid and out-of-control inflation', 'A fixed exchange rate system', 'A decrease in the money supply'], correct: 1 },
    { q: 'What does a monopoly describe?', choices: ['A market with many small competing sellers', 'A market dominated by a single seller', 'A market with no buyers', 'A market regulated only by tariffs'], correct: 1 },
    { q: 'What does an oligopoly describe?', choices: ['A market dominated by a small number of large sellers', 'A market with a single buyer only', 'A market with unlimited new entrants', 'A market with fixed government prices'], correct: 0 },
    { q: "What does 'trade surplus' mean?", choices: ['When a country imports more than it exports', 'When a country exports more than it imports', "A company's annual profit", 'A government running a budget surplus'], correct: 1 },
    { q: "What is the World Bank's primary purpose?", choices: ['Setting global interest rates', 'Providing financial and technical assistance to developing countries', 'Printing international currency', 'Regulating stock exchanges'], correct: 1 },
    { q: 'What does the IMF primarily do?', choices: ['Issues a global currency', 'Promotes international monetary cooperation and financial stability', 'Regulates individual national elections', 'Sets tariffs between countries'], correct: 1 },
    { q: "What is 'real GDP' adjusted for, compared to nominal GDP?", choices: ['Population size', 'Inflation', 'Exchange rates', 'Interest rates'], correct: 1 },
    { q: "What does 'externality' mean in economics?", choices: ['A company\'s foreign revenue', 'A cost or benefit affecting a third party not involved in a transaction', "A country's trade balance", 'A tax refund'], correct: 1 },
    { q: "What does 'elasticity of demand' measure?", choices: ['How much a currency fluctuates', 'How much quantity demanded changes in response to a price change', 'A company\'s stock volatility', 'The speed of economic growth'], correct: 1 },
    { q: 'What does fiat currency mean?', choices: ['Currency backed by gold reserves', 'Currency without intrinsic value, backed by government decree', 'A currency used only for exports', 'A digital-only currency'], correct: 1 },
    { q: 'What is a recessionary gap?', choices: ['When actual GDP exceeds potential GDP', 'When actual GDP is below potential GDP', 'A gap in the trade balance', 'A shortfall in tax revenue only'], correct: 1 },
    { q: 'What does "purchasing power" refer to?', choices: ["A country's total gold reserves", 'The value of currency expressed in terms of the goods and services it can buy', 'A company\'s buying department', "A bank's lending limit"], correct: 1 },
    { q: 'What is progressive taxation?', choices: ['A tax rate that stays the same for everyone', 'A tax rate that increases as income increases', 'A tax only on imports', 'A one-time tax on wealth'], correct: 1 },
  ],

  politics: [
    { q: 'Who was the first President of the United States?', choices: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'], correct: 2 },
    { q: 'How many justices currently sit on the US Supreme Court?', choices: ['7', '9', '11', '13'], correct: 1 },
    { q: 'How long is a US Senate term?', choices: ['2 years', '4 years', '6 years', '8 years'], correct: 2 },
    { q: 'How long is a term for a member of the US House of Representatives?', choices: ['2 years', '4 years', '6 years', '10 years'], correct: 0 },
    { q: 'What document begins with the words "We the People"?', choices: ['The Declaration of Independence', 'The US Constitution', 'The Bill of Rights', 'The Federalist Papers'], correct: 1 },
    { q: 'How many amendments are in the US Bill of Rights?', choices: ['5', '8', '10', '12'], correct: 2 },
    { q: 'What is the maximum number of terms a US President can serve?', choices: ['1', '2', '3', 'Unlimited'], correct: 1 },
    { q: 'In what year did the United States declare independence?', choices: ['1774', '1776', '1783', '1789'], correct: 1 },
    { q: 'How many states make up the United States?', choices: ['48', '49', '50', '52'], correct: 2 },
    { q: "What is the name of the US Congress's lower chamber?", choices: ['The Senate', 'The House of Representatives', 'The Cabinet', 'The Assembly'], correct: 1 },
    { q: 'Which US President served the longest in office?', choices: ['Abraham Lincoln', 'Franklin D. Roosevelt', 'Theodore Roosevelt', 'Woodrow Wilson'], correct: 1 },
    { q: 'What city is the capital of the United States?', choices: ['New York City', 'Philadelphia', 'Washington, D.C.', 'Boston'], correct: 2 },
    { q: 'Who is generally credited as the primary author of the Declaration of Independence?', choices: ['George Washington', 'Thomas Jefferson', 'John Hancock', 'James Madison'], correct: 1 },
    { q: 'What is the term length of a UK Prime Minister fixed at, by law?', choices: ['There is no fixed term — elections can be called earlier', '4 years exactly', '6 years exactly', '10 years exactly'], correct: 0 },
    { q: 'How many members does the United Nations Security Council have permanently (with veto power)?', choices: ['3', '5', '7', '10'], correct: 1 },
    { q: 'What is the minimum age to serve as US President?', choices: ['30', '35', '40', '21'], correct: 1 },
    { q: 'Which branch of the US government is the Supreme Court part of?', choices: ['Legislative', 'Executive', 'Judicial', 'Administrative'], correct: 2 },
    { q: 'How many electoral votes does a US presidential candidate need to win, out of 538?', choices: ['218', '270', '300', '400'], correct: 1 },
    { q: 'What war ended with the Treaty of Paris in 1783?', choices: ['The Civil War', 'The American Revolutionary War', 'World War I', 'The War of 1812'], correct: 1 },
    { q: 'Who was the President of the United States during the Civil War?', choices: ['Andrew Jackson', 'Abraham Lincoln', 'Ulysses S. Grant', 'James Buchanan'], correct: 1 },
    { q: 'How many total voting members are in the US House of Representatives?', choices: ['335', '385', '435', '535'], correct: 2 },
    { q: 'How many total members are in the US Senate?', choices: ['50', '100', '150', '200'], correct: 1 },
    { q: "What is required for the US Congress to override a presidential veto?", choices: ['A simple majority in one chamber', 'A two-thirds majority vote in both chambers', 'Unanimous consent', 'A public referendum'], correct: 1 },
    { q: 'Who is next in the presidential line of succession after the Vice President?', choices: ['The Chief Justice', 'The Speaker of the House', 'The Secretary of State', 'The Senate Majority Leader'], correct: 1 },
    { q: 'How many amendments does the US Constitution currently have in total?', choices: ['21', '27', '33', '40'], correct: 1 },
    { q: 'What is the term length for a US Supreme Court Justice?', choices: ['10 years', '20 years', 'Life tenure, with no fixed term', 'Until age 65'], correct: 2 },
    { q: 'Which amendment abolished slavery in the United States?', choices: ['The 13th Amendment', 'The 14th Amendment', 'The 15th Amendment', 'The 19th Amendment'], correct: 0 },
    { q: 'Which amendment granted women the right to vote in the United States?', choices: ['The 15th Amendment', 'The 17th Amendment', 'The 19th Amendment', 'The 21st Amendment'], correct: 2 },
    { q: 'What voting age did the 26th Amendment establish?', choices: ['16', '18', '21', '25'], correct: 1 },
    { q: 'How many total electoral votes are there in the US Electoral College?', choices: ['435', '500', '538', '600'], correct: 2 },
    { q: 'What is the formal process for removing a President from office called?', choices: ['Recall', 'Impeachment', 'Censure', 'Nullification'], correct: 1 },
    { q: 'Which chamber of Congress has the sole power to impeach a President?', choices: ['The Senate', 'The House of Representatives', 'The Supreme Court', 'The Cabinet'], correct: 1 },
    { q: 'Which chamber of Congress conducts an impeachment trial?', choices: ['The House of Representatives', 'The Senate', 'The Supreme Court', 'The Electoral College'], correct: 1 },
    { q: "What is the collective name for the US President's senior advisors?", choices: ['The Cabinet', 'The Congress', 'The Committee', 'The Council'], correct: 0 },
    { q: 'How often is a national census conducted in the United States?', choices: ['Every 4 years', 'Every 5 years', 'Every 10 years', 'Every 20 years'], correct: 2 },
    { q: 'What is the minimum age to serve in the US Senate?', choices: ['25', '30', '35', '40'], correct: 1 },
    { q: 'What is the minimum age to serve in the US House of Representatives?', choices: ['21', '25', '30', '35'], correct: 1 },
    { q: 'Which US President is the only one to serve two non-consecutive terms?', choices: ['Theodore Roosevelt', 'Grover Cleveland', 'Woodrow Wilson', 'William Taft'], correct: 1 },
    { q: "What is a 'filibuster' used for in the US Senate?", choices: ['To immediately end a debate', 'To delay or block a vote through extended debate', 'To call a special election', 'To remove a sitting Senator'], correct: 1 },
  ],

  sports: [
    { q: 'How many players are on a basketball court per team during play?', choices: ['4', '5', '6', '7'], correct: 1 },
    { q: 'How many minutes are in a regulation soccer match (excluding stoppage time)?', choices: ['60', '80', '90', '120'], correct: 2 },
    { q: 'What sport is played at Wimbledon?', choices: ['Golf', 'Tennis', 'Cricket', 'Rugby'], correct: 1 },
    { q: 'How many rings are on the Olympic flag?', choices: ['4', '5', '6', '7'], correct: 1 },
    { q: 'How many holes are played in a standard round of golf?', choices: ['9', '16', '18', '21'], correct: 2 },
    { q: "What is a 'hat-trick' in soccer or hockey?", choices: ['Winning three games in a row', 'Scoring three goals in a single game', 'A three-minute penalty', 'A team\'s third championship'], correct: 1 },
    { q: 'How many points is a touchdown worth in American football (before the extra point)?', choices: ['3', '6', '7', '2'], correct: 1 },
    { q: 'Which country has won the most FIFA World Cups?', choices: ['Germany', 'Argentina', 'Brazil', 'Italy'], correct: 2 },
    { q: 'How many players are on a standard soccer team on the field (including goalkeeper)?', choices: ['9', '10', '11', '12'], correct: 2 },
    { q: 'What is the maximum possible score in a single game of ten-pin bowling?', choices: ['200', '250', '300', '350'], correct: 2 },
    { q: 'How often are the Summer Olympic Games held?', choices: ['Every 2 years', 'Every 4 years', 'Every 5 years', 'Every 6 years'], correct: 1 },
    { q: 'In tennis, what is a score of zero called?', choices: ['Nil', 'Love', 'Deuce', 'Ace'], correct: 1 },
    { q: 'How many players are on a baseball team on the field defensively?', choices: ['8', '9', '10', '11'], correct: 1 },
    { q: 'What is the term for a score of one under par on a single golf hole?', choices: ['Bogey', 'Eagle', 'Birdie', 'Albatross'], correct: 2 },
    { q: 'How long does a standard boxing round last?', choices: ['1 minute', '2 minutes', '3 minutes', '5 minutes'], correct: 2 },
    { q: 'In which sport would you perform a "slam dunk"?', choices: ['Volleyball', 'Basketball', 'Handball', 'Badminton'], correct: 1 },
    { q: 'How many periods are in a standard game of ice hockey?', choices: ['2', '3', '4', '5'], correct: 1 },
    { q: 'What is the diameter concept of a "full court press" associated with?', choices: ['Basketball', 'Baseball', 'Swimming', 'Golf'], correct: 0 },
    { q: 'How many Grand Slam tennis tournaments are there per year?', choices: ['2', '3', '4', '5'], correct: 2 },
    { q: 'What color card signals a player ejection in soccer?', choices: ['Yellow', 'Red', 'Blue', 'Black'], correct: 1 },
    { q: 'How many players are on the ice per team in ice hockey (excluding the goalie)?', choices: ['4', '5', '6', '7'], correct: 1 },
    { q: 'What is the maximum number of clubs a golfer can carry per standard rules?', choices: ['10', '12', '14', '16'], correct: 2 },
    { q: 'How many minutes are in a regulation NBA basketball game?', choices: ['40', '44', '48', '52'], correct: 2 },
    { q: 'How many quarters make up an NBA basketball game?', choices: ['2', '3', '4', '5'], correct: 2 },
    { q: 'How many players are on a volleyball team on the court per side?', choices: ['5', '6', '7', '8'], correct: 1 },
    { q: 'What is the standard length of an Olympic swimming pool?', choices: ['25 meters', '50 meters', '100 meters', '200 meters'], correct: 1 },
    { q: 'How many rounds are in a standard professional boxing championship bout?', choices: ['8', '10', '12', '15'], correct: 2 },
    { q: "What sport uses a 'shuttlecock'?", choices: ['Table tennis', 'Badminton', 'Squash', 'Racquetball'], correct: 1 },
    { q: 'In cricket, how many players are on each team?', choices: ['9', '10', '11', '12'], correct: 2 },
    { q: 'What is the term for scoring zero runs in a cricket innings?', choices: ['A duck', 'A blank', 'A zero', 'A maiden'], correct: 0 },
    { q: 'How many events make up a decathlon?', choices: ['7', '8', '10', '12'], correct: 2 },
    { q: 'What is it called when a bowler gets three strikes in a row in ten-pin bowling?', choices: ['A hat-trick', 'A turkey', 'A triple', 'A strike-out'], correct: 1 },
    { q: 'How many players make up a rugby union team on the field?', choices: ['13', '14', '15', '16'], correct: 2 },
    { q: 'What color belt typically signifies the highest rank in most judo and karate systems?', choices: ['Red', 'Brown', 'Black', 'Gold'], correct: 2 },
    { q: 'In Formula 1 racing, what does the checkered flag signal?', choices: ['A red-flag stoppage', 'The end of the race', 'A pit-stop warning', 'A false start'], correct: 1 },
    { q: 'What is the standard distance of a marathon?', choices: ['20 miles', '24.2 miles', '26.2 miles', '30 miles'], correct: 2 },
    { q: 'How many bases are on a standard baseball diamond, including home plate?', choices: ['3', '4', '5', '6'], correct: 1 },
    { q: "What is a score of zero-zero called in tennis?", choices: ['Deuce', 'Love-all', 'Nil-all', 'Ace-all'], correct: 1 },
    { q: 'In the NFL, how many downs does a team get to advance 10 yards?', choices: ['3', '4', '5', '6'], correct: 1 },
  ],
};

const CATEGORIES = Object.keys(QUESTIONS);

module.exports = { QUESTIONS, CATEGORIES };
